<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>photo_album.Application</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\photo-album.Domain\photo-album.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Contracts\Repositories\" />
      <Folder Include="Dto\Requests\" />
      <Folder Include="Dto\Responses\" />
      <Folder Include="MapperProfiles\" />
      <Folder Include="UseCases\CommandHandlers\" />
      <Folder Include="UseCases\Commands\" />
      <Folder Include="UseCases\Queries\" />
      <Folder Include="UseCases\QueryHandlers\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="16.2.0" />
      <PackageReference Include="FluentValidation" Version="12.1.1" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
      <PackageReference Include="MediatR" Version="14.2.0" />
    </ItemGroup>

</Project>
